### ISSUE TITLE
run Jobs over CLI

### ISSUE THREAD

**Issue by karloscampus** [melentye/flink-kubernetes#1]
im trying to run a job via the flink run command inside the jobmanager container:
`./cluster/kubectl.sh exec -it jobmanager-controller-6cn4p bash`
then
`flink run -c cloudTest.Consumer -j /cluster-test.jar -topic cloudtest -brokers kafka.default.svc.cluster.local:9092 -groupId testConsumer`
but i just getting an timeout exception from the blobserver :/

> org.apache.flink.client.program.ProgramInvocationException: The program execution failed: Could not upload the jar files to the job manager.
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:409)
	at org.apache.flink.client.program.StandaloneClusterClient.submitJob(StandaloneClusterClient.java:95)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:382)
	at org.apache.flink.streaming.api.environment.StreamContextEnvironment.execute(StreamContextEnvironment.java:68)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1429)
	at de.bonprix.cloudTest.Consumer.main(Consumer.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:509)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:403)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:320)
	at org.apache.flink.client.CliFrontend.executeProgram(CliFrontend.java:777)
	at org.apache.flink.client.CliFrontend.run(CliFrontend.java:253)
	at org.apache.flink.client.CliFrontend.parseParameters(CliFrontend.java:1005)
	at org.apache.flink.client.CliFrontend.main(CliFrontend.java:1048)
Caused by: org.apache.flink.runtime.client.JobSubmissionException: Could not upload the jar files to the job manager.
	at org.apache.flink.runtime.client.JobClientActor$2.call(JobClientActor.java:375)
	at akka.dispatch.Futures$$anonfun$future$1.apply(Future.scala:95)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.IOException: Could not retrieve the JobManager's blob port.
	at org.apache.flink.runtime.blob.BlobClient.uploadJarFiles(BlobClient.java:706)
	at org.apache.flink.runtime.jobgraph.JobGraph.uploadUserJars(JobGraph.java:556)
	at org.apache.flink.runtime.client.JobClientActor$2.call(JobClientActor.java:369)
	... 9 more
Caused by: java.io.IOException: Could not connect to BlobServer at address /10.247.224.126:44056
	at org.apache.flink.runtime.blob.BlobClient.<init>(BlobClient.java:88)
	at org.apache.flink.runtime.blob.BlobClient.uploadJarFiles(BlobClient.java:724)
	at org.apache.flink.runtime.blob.BlobClient.uploadJarFiles(BlobClient.java:701)
	... 11 more
Caused by: java.net.ConnectException: Operation timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at org.apache.flink.runtime.blob.BlobClient.<init>(BlobClient.java:84)

seems that the Port of the Blob-server needs to be pinned and exposed?!

**Comment by melentye** [comment]
@karloscampus thanks for reporting this, you're right about the BLOB server. 

I've tuned the melentye/flink:1.1.3-custom-akka3 Docker image to accept arbitrary config file overrides: https://github.com/melentye/flink-docker/commit/acd1dda2eccbba8d9518d2faf305f74d3ba920ea

And used that to pin the BLOB server port in K8S: https://github.com/melentye/flink-kubernetes/commit/bee67ec0160785e3430444f404bc1b7642a4145f

Can you check if that works better for you now?

**Comment by karloscampus** [comment]
Thx a lot, it works now ;D
